/*
 * Created on 24 lis 2014 ( Time 20:42:09 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package pl.pwl.samouczek.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import pl.pwl.samouczek.orm.jpa.LessonEntity;
import pl.pwl.samouczek.persistence.commons.jpa.GenericJpaService;
import pl.pwl.samouczek.persistence.commons.jpa.JpaOperation;
import pl.pwl.samouczek.persistence.services.LessonPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Lesson" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class LessonPersistenceJPA extends GenericJpaService<LessonEntity, Integer> implements LessonPersistence {

	/**
	 * Constructor
	 */
	public LessonPersistenceJPA() {
		super(LessonEntity.class);
	}

	@Override
	public LessonEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(LessonEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("LessonEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
